= Исключения =
Для работы с исключениями в DForth нужно подключить библиотеку exceptions.df
{{{
str" exceptions.df" evaluate-file
}}}
После этого становятся доступными две команды: throw и catch.
{{{
catch ( ... xt -- ... i ) выполняет команду со стека (помещённую туда, например, командой ['']). В случае если исключения не было на стеке будет помещено 0. Если же сработало исключение (командой throw) то указатель рабочего и возвратного стека будут возвращены в состояние которое имели перед выполнением команды catch и на стек будет помещён код исключения
throw ( ... i -- ... i ) последовательно выходит из функций до тех пор пока не встретит вызов командой catch. После чего передаёт управление в неё. 
}}}
                     
